version: "3.9"

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    container_name: backend

  frontend:
    build: ./frontend
    ports:
      - "5173:5173" # ou 3001:3000 se quiser mudar
    depends_on:
      - backend


volumes:
  mongo_data:
